with hiredatasource as ( 
  SELECT 
    *
from bounty_jobs_enhanced.bountyjobs_sql_hire
)
,submission as (
select 
    CAST(NULL AS INTEGER) AS "SUBMISSION ID",
    CAST(NULL AS TEXT) AS "DIVERSITY_STATUS",
    CAST(NULL AS INTEGER) AS "RECRUITER AGENCY ID",
    CAST(NULL AS TEXT) AS "CONT HIRING MANAGER NAME",
    CAST(NULL AS TEXT) AS "SANOFI EMAIL FILTER",
    CAST(NULL AS TEXT) AS "POSTING USER FIRST NAME",
    CAST(NULL AS TEXT) AS "POSTING USER LAST NAME",
    CAST(NULL AS TEXT) AS "EMPLOYER COMPANY SIZE",
    CAST(NULL AS TEXT) AS "AGENCY REFERRAL CODE",
    CAST(NULL AS TEXT) AS "EMPLOYER REFERRAL CODE",
    CAST(NULL AS TIMESTAMP) AS "RECRUITER INITIAL ACTIVATION DATE",
    CAST(NULL AS TIMESTAMP) AS "RECRUITER CREATION DATE",
    CAST(NULL AS TIMESTAMP) AS "READ BY HIRING MANAGER",
    CAST(NULL AS TEXT) AS "SUBMISSION NOTE",
    CAST(NULL AS TEXT) AS "SUBMISSION VIEWED",
    CAST(NULL AS TEXT) AS "POSTING BUSINESS UNIT 3",
    CAST(NULL AS TEXT) AS "SUBMISSION TYPE",
    CAST(NULL AS TEXT) AS "POSTING HANDLER",
    CAST(NULL AS TEXT) AS "FIRST STATUS CHANGE",
    CAST(NULL AS TIMESTAMP) AS "FIRST STATUS CHANGE DATE",
    CAST(NULL AS TEXT) AS "SECOND STATUS CHANGE",
    CAST(NULL AS TIMESTAMP) AS "SECOND STATUS CHANGE DATE",
    CAST(NULL AS TEXT) AS "EXECUTIVE SEGMENT",
    CAST(NULL AS TEXT) AS "SUBMISSION BUSINESS HOURS CREATION",
    CAST(NULL AS TEXT) AS "SUBMISSION BUSINESS HOURS FIRST CHANGE",
    CAST(NULL AS TIMESTAMP) AS "SUBMISSION CREATE DATE",
    CAST(NULL AS TEXT) AS "SUBMISSION STATUS",
    CAST(NULL AS INTEGER) AS "POSTING BOUNTYJOBS ID",
    CAST(NULL AS TIMESTAMP) AS "POSTING CREATION DATE",
    CAST(NULL AS TEXT) AS "POSTING TITLE",
    CAST(NULL AS TEXT) AS "POSTING STATUS",
    CAST(NULL AS INTEGER) AS "RECRUITER USER ID",
    CAST(NULL AS TEXT) AS "RECRUITER FULL NAME",
    CAST(NULL AS INTEGER) AS "CANDIDATE ID",
    CAST(NULL AS TEXT) AS "CANDIDATE FULL NAME",
    CAST(NULL AS TEXT) AS "CANDIDATE TITLE",
    CAST(NULL AS TEXT) AS "POSTING PRODUCT",
    CAST(NULL AS TEXT) AS "POSTING SOURCE CHANNEL",
    CAST(NULL AS TEXT) AS "POSTING SOURCE DETAIL",
    CAST(NULL AS TEXT) AS "POSTING EXTERNAL ID",
    CAST(NULL AS INTEGER) AS "POSTING USER ID",
    CAST(NULL AS TEXT) AS "POSTING USER FULLNAME",
    CAST(NULL AS TEXT) AS "POSTING COSOURCE CLIENT NAME",
    CAST(NULL AS INTEGER) AS "POSTING NUMBER OF POSITIONS",
    CAST(NULL AS TEXT) AS "POSTING BUSINESS UNIT",
    CAST(NULL AS TEXT) AS "POSTING INDUSTRY PARENT",
    CAST(NULL AS TEXT) AS "POSTING INDUSTRY CHILD",
    CAST(NULL AS TEXT) AS "POSTING JOB CATEGORY PARENT",
    CAST(NULL AS TEXT) AS "POSTING JOB CATEGORY CHILD",
    CAST(NULL AS TEXT) AS "POSTING FEE MODEL",
    CAST(NULL AS TEXT) AS "POSTING FEE TYPE",
    CAST(NULL AS TEXT) AS "POSTING FEE PERCENTAGE",
    CAST(NULL AS TEXT) AS "POSTING CURRENCY CODE",
    CAST(NULL AS DECIMAL) AS "POSTING FEE AMOUNT",
    CAST(NULL AS DECIMAL) AS "POSTING SALARY MINIMUM RANGE",
    CAST(NULL AS DECIMAL) AS "POSTING SALARY MAXIMUM RANGE",
    CAST(NULL AS INTEGER) AS "POSTING BONUS ELIGIBLE",
    CAST(NULL AS DECIMAL) AS "POSTING BONUS MINIMUM RANGE",
    CAST(NULL AS DECIMAL) AS "POSTING BONUS MAXIMUM RANGE",
    CAST(NULL AS INTEGER) AS "POSTING COMMISSION ELIGIBLE",
    CAST(NULL AS INTEGER) AS "POSTING OVERTIME ELIGIBLE",
    CAST(NULL AS TEXT) AS "POSTING EMPLOYMENT TYPE",
    CAST(NULL AS TEXT) AS "POSTING HOURS PER WEEK",
    CAST(NULL AS TEXT) AS "POSTING BENEFITS",
    CAST(NULL AS INTEGER) AS "POSTING INTERVIEW REIMBURSED",
    CAST(NULL AS TEXT) AS "POSTING RELOCATION ASSISTANCE",
    CAST(NULL AS INTEGER) AS "POSTING OFFCCP COMPLIANCE",
    CAST(NULL AS INTEGER) AS "POSTING REMOTE POSITION",
    CAST(NULL AS TEXT) AS "POSTING EDUCATION LEVEL",
    CAST(NULL AS TEXT) AS "POSTING YEARS EXPERIENCE",
    CAST(NULL AS TEXT) AS "POSTING SENIORITY",
    CAST(NULL AS INTEGER) AS "POSTING MANAGEMENT EXPERIENCE",
    CAST(NULL AS INTEGER) AS "POSTING VISA CANDIDATES CONSIDERED",
    CAST(NULL AS INTEGER) AS "POSTING SECURITY CLEARANCE REQUIRED",
    CAST(NULL AS TEXT) AS "POSTING TRAVEL REQUIREMENTS",
    CAST(NULL AS TEXT) AS "POSTING VISIBILITY",
    CAST(NULL AS INTEGER) AS "POSTING PRIORITY",
    CAST(NULL AS TEXT) AS "POSTING REPOST TYPE",
    CAST(NULL AS TIMESTAMP) AS "EMPLOYER FIRST POST DATE",
    CAST(NULL AS INTEGER) AS "EMPLOYER AGE",
    CAST(NULL AS TEXT) AS "EMPLOYER AGE COHORT",
    CAST(NULL AS INTEGER) AS "EMPLOYER PAYMENT TERMS",
    CAST(NULL AS TEXT) AS "POSTING INTAKE SESSION STATUS",
    CAST(NULL AS DATE) AS "POSTING INTAKE SESSION DATETIME",
    CAST(NULL AS TEXT) AS "CANDIDATE EMAIL",
    CAST(NULL AS INTEGER) AS "EMPLOYER COMPANY ID",
    CAST(NULL AS TEXT) AS "EMPLOYER COMPANY NAME",
    CAST(NULL AS TEXT) AS "ACCOUNT DIRECTOR",
    CAST(NULL AS TEXT) AS "ACCOUNT DIRECTOR EMAIL",
    CAST(NULL AS TEXT) AS "ACCOUNT MANAGER",
    CAST(NULL AS TEXT) AS "ACCOUNT MANAGER EMAIL",
    CAST(NULL AS TEXT) AS "RECRUITER AGENCY NAME",
    CAST(NULL AS INTEGER) AS "JOB POSTING ID",
    CAST(NULL AS TEXT) AS "RECRUITER EMAIL ADDRESS",
    CAST(NULL AS TEXT) AS "POSTING CITIES",
    CAST(NULL AS TEXT) AS "POSTING REGIONS",
    CAST(NULL AS TEXT) AS "POSTING STATES",
    CAST(NULL AS TEXT) AS "POSTING COUNTRIES",
    CAST(NULL AS TEXT) AS "POSTING FULL LOCATIONS",
    CAST(NULL AS TIMESTAMP) as "SUBMISSION BUSINESS HOURS CREATION DATE",
    CAST(NULL AS TIMESTAMP) as "SUBMISSION BUSINESS HOURS FIRST CHANGE DATE",
    CAST(NULL AS TEXT) AS "ADDRESS_1",
    CAST(NULL AS TEXT) AS "ADDRESS_2",
    CAST(NULL AS TEXT) AS "POSTAL_CODE",
    CAST(NULL AS TEXT) AS "RECRUITER CITY",
    CAST(NULL AS TEXT) AS "RECRUITER STATE",
    CAST(NULL AS TEXT) AS "RECRUITER CURRENCY CODE",
    CAST(NULL AS TEXT) AS "RECRUITER PHONE",
    CAST(NULL AS TEXT) AS "EMPLOYER ADDRESS 1",
    CAST(NULL AS TEXT) AS "EMPLOYER ADDRESS 2",
    CAST(NULL AS TEXT) AS "EMPLOYER CITY",
    CAST(NULL AS TEXT) AS "EMPLOYER STATE",
    CAST(NULL AS TEXT) AS "EMPLOYER POSTAL CODE",
    CAST(NULL AS TIMESTAMP) AS "HIRE MOST RECENT DATE OF",
    CAST(NULL AS TEXT) AS "SUBSCRIPTION TYPE",
    CAST(NULL AS TEXT) AS "WORKER TYPE",
    CAST(NULL AS TEXT) AS "EMPLOYER COUNTRY",
    CAST(NULL AS TEXT) AS "EMPLOYER OFCCP STATUS",
    CAST(NULL AS TEXT) AS "EMPLOYER EMAIL",
    CAST(NULL AS TEXT) AS "FURTHEST STATUS REACHED",
    CAST(NULL AS TIMESTAMP) AS "FURTHEST STATUS REACHED DATE",
    CAST(NULL AS TIMESTAMP) AS "ATS REJECTION DATE",
    CAST(NULL AS TIMESTAMP) AS "APPEAL DATE",
    CAST(NULL AS TEXT) AS "Company Filter",
    CAST(NULL AS INTEGER) AS "Years of Experience Sort",
    CAST(NULL AS DECIMAL) AS "WORKER BILL RATE",
    CAST(NULL AS DECIMAL) AS "WORKER PAY RATE",
    CAST(NULL AS TEXT) AS "WORKER ASSIGNMENT STATUS",
    CAST(NULL AS TEXT) AS "EOR NAME",
    CAST(NULL AS TEXT) AS "BUSINESS UNIT 2",
    CAST(NULL AS TIMESTAMP) AS "SUBMISSION MODIFIED DATE",
    CAST(NULL AS DECIMAL) AS "POSTING FEE AMOUNT UNCONVERTED",
    CAST(NULL AS TEXT) AS "PAUSED",
    CAST(NULL AS TIMESTAMP) AS "PAUSED DATE"
  )
,joindatacomponent as (
select * 
from hiredatasource hs 
left outer join submission s on hs.submission_id = s."SUBMISSION ID"
)
,agencyrecruitercolumns as (
select 
"RECRUITER USER ID", 
"diversity_status" as "DIVERSITY STATUS",
"recruiter country",
"recruiter agency name" as "RECRUITER AGENCY (FROM RA) - DO NOT USE",
"recruiter  last login"
from bounty_jobs_enhanced.agency_recruiter
)
, joindata1compenent as (
SELECT 
    jdc.*,
    agc."DIVERSITY STATUS",
    agc."recruiter country" as "RECRUITER COUNTRY",
    agc."RECRUITER AGENCY (FROM RA) - DO NOT USE",
    agc."recruiter  last login"
from joindatacomponent jdc 
left outer join agencyrecruitercolumns agc on jdc."RECRUITER USER ID" = agc."RECRUITER USER ID"
)
, AWARD_DATA_FILTER_COMPONENT as (
select *
from dbt_noumanjilani.bountyjobs_workflow_award
where
"award response status" = 'Accepted'
)
, SelectColumns1Component as (
select 
        "AWARD SUBMISSION ID",
		"AWARD FEE AMOUNT", 
		"AWARD EMPLOYER NET",
		"POSTING USER FULLNAME" AS "POSTING USER FULLNAME1",
		"USER EMAIL ADDRESS" AS "POSTING USER EMAIL ADDRESS",
		"AWARD RESPONSE STATUS",
		"AWARD REQUEST DATE"
 from AWARD_DATA_FILTER_COMPONENT
)
, GroupbyComponent as (
select
      s."AWARD SUBMISSION ID" ,
      s."AWARD FEE AMOUNT",
      s."AWARD EMPLOYER NET",
      s."POSTING USER FULLNAME1" ,
      s."POSTING USER EMAIL ADDRESS" as "POSTING USER EMAIL",
      s."AWARD RESPONSE STATUS"
FROM ( select
           *,
            ROW_NUMBER() OVER (
                PARTITION BY "award submission id"
                ORDER BY "AWARD REQUEST DATE" ASC
            ) AS row_num
        FROM SelectColumns1Component 
    ) s
    WHERE s.row_num = 1
)
,JoinData2Component as (
select 
     j1d.*,
    gbc."AWARD FEE AMOUNT",
    gbc."AWARD EMPLOYER NET",
    gbc."POSTING USER FULLNAME1",
    gbc."POSTING USER EMAIL",
    gbc."AWARD RESPONSE STATUS"
from joindata1compenent j1d 
left outer join GroupbyComponent gbc on j1d.SUBMISSION_ID = gbc."award submission id"
)
,FilterRows1_and_SelectColumns7 as (
select 
award_question_id as "AWARD QUESTION ID",
answer as "PURCHASE ORDER",
submission_id as "HIRE SUBMISSION ID",
question as "AWARD QUESTION"
from bounty_jobs_enhanced.bountyjobs_sql_award_answer
where
question = 'Purchase Order'
)
,FilterRows2_and_SelectColumns8 as (
select 
answer as "COST CENTER NUMBER",
submission_id as "HIRE SUBMISSION ID"
from bounty_jobs_enhanced.bountyjobs_sql_award_answer
where
question = 'Cost Center Number'
)
,JoinData3Component as (
select *
from JoinData2Component j2c
left outer join FilterRows1_and_SelectColumns7 fs7 on j2c.SUBMISSION_ID = fs7. "HIRE SUBMISSION ID"
)
,JoinData7Component as (
select
     j3c.*,
     fs8."COST CENTER NUMBER"
from JoinData3Component j3c 
left outer join FilterRows2_and_SelectColumns8 fs8 on j3c.SUBMISSION_ID = fs8. "HIRE SUBMISSION ID"
)
,SelectColumns as (
Select 
"HIRE_ID",
"SUBMISSION_ID" as "HIRE SUBMISSION ID",
"CREATED_BY" as "HIRE SUBMISSION CREATED BY",
"SUBMISSION CREATE DATE" as "HIRE SUBMISSION CREATED DATE",
"COMPENSATION_OWNER_ID" as "HIRE SUBMISSION COMPENSATION OWNER",
"CURRENCY_CODE" as "HIRE CURRENCY CODE",
"SALARY_PERCENT_AWARD" as "HIRE SALARY PERCENT AWARD",
"SALARY" as "HIRE SALARY UNCONVERTED",
"SALARY_USD_CONVERTED" as "HIRE SALARY",
"CANDIDATE_START_DATE" as "HIRE CANDIDATE START DATE",
"PURCHASE_ORDER" as "HIRE PURCHASE ORDER",
"AWARD" as "HIRE AWARD UNCONVERTED",
"AWARD_USD_CONVERTED" as "HIRE AWARD",
"PAYMENT_STATUS" as "HIRE PAYMENT STATUS",
"INVOICE_NUMBER" as "HIRE INVOICE NUMBER",
"AWARD_STATUS" as "HIRE AWARD STATUS",
"PAYMENT_DATE" as "HIRE PAYMENT DATE",
"PAYMENT_CREATOR_ID" as "HIRE PAYMENT CREATOR ID",
"PAYMENT_MODIFIER_ID" as "HIRE PAYMENT MODIFIER ID",
"PAYMENT_MODIFICATION_DATE" as "HIRE PAYMENT MODIFICATION DATE",
"LAST_PAYMENT_DATE" as "HIRE LAST PAYMENT DATE",
"COUNT_AS_ON_TIME" as "HIRE PAYMENT ON TIME",
"AWARD_ACCEPTOR" as "HIRE AWARD ACCEPTOR",
"AWARD_ACCEPTED_DATE" as "HIRE AWARD ACCEPTED DATE",
"TYPE_OF_PLACEMENT" as "HIRE PLACEMENT TYPE",
"BOUNTYJOBS_NET" as "HIRE BOUNTYJOBS NET UNCONVERTED",
"BOUNTYJOBS_NET_USD_CONVERTED" as "HIRE BOUNTYJOBS NET",
"RECRUITER_NET" as "HIRE RECRUITER NET UNCONVERTED",
"RECRUITER_NET_USD_CONVERTED" as "HIRE RECRUITER NET",
"EMPLOYER_NET" as "HIRE EMPLOYER NET UNCONVERTED",
"EMPLOYER_NET_USD_CONVERTED" as "HIRE EMPLOYER NET",
"SUBMISSION ID",
"SUBMISSION STATUS",
"POSTING BOUNTYJOBS ID",
"POSTING CREATION DATE",
"POSTING TITLE",
"POSTING STATUS",
"RECRUITER USER ID",
"RECRUITER FULL NAME",
"CANDIDATE ID",
"CANDIDATE FULL NAME",
"CANDIDATE TITLE",
"POSTING PRODUCT",
"POSTING SOURCE CHANNEL",
"POSTING SOURCE DETAIL",
"POSTING EXTERNAL ID",
"POSTING USER ID",
"POSTING USER FULLNAME",
"POSTING COSOURCE CLIENT NAME",
"POSTING NUMBER OF POSITIONS",
"POSTING BUSINESS UNIT",
"POSTING INDUSTRY PARENT",
"POSTING INDUSTRY CHILD",
"POSTING JOB CATEGORY PARENT",
"POSTING JOB CATEGORY CHILD",
"POSTING FEE MODEL",
"POSTING FEE TYPE",
"POSTING FEE PERCENTAGE",
"POSTING CURRENCY CODE",
"POSTING FEE AMOUNT",
"POSTING SALARY MINIMUM RANGE",
"POSTING SALARY MAXIMUM RANGE",
"POSTING BONUS ELIGIBLE",
"POSTING BONUS MINIMUM RANGE",
"POSTING BONUS MAXIMUM RANGE",
"POSTING COMMISSION ELIGIBLE",
"POSTING OVERTIME ELIGIBLE",
"POSTING EMPLOYMENT TYPE",
"POSTING HOURS PER WEEK",
"POSTING BENEFITS",
"POSTING INTERVIEW REIMBURSED",
"POSTING RELOCATION ASSISTANCE",
"POSTING OFFCCP COMPLIANCE",
"POSTING REMOTE POSITION",
"POSTING EDUCATION LEVEL",
"POSTING YEARS EXPERIENCE",
"POSTING SENIORITY",
"POSTING MANAGEMENT EXPERIENCE",
"POSTING VISA CANDIDATES CONSIDERED",
"POSTING SECURITY CLEARANCE REQUIRED",
"POSTING TRAVEL REQUIREMENTS",
"POSTING VISIBILITY",
"POSTING PRIORITY",
"POSTING REPOST TYPE",
"EMPLOYER FIRST POST DATE",
"EMPLOYER AGE",
"EMPLOYER AGE COHORT",
"EMPLOYER PAYMENT TERMS",
"POSTING INTAKE SESSION STATUS",
"POSTING INTAKE SESSION DATETIME",
"CANDIDATE EMAIL",
"EMPLOYER COMPANY ID",
"EMPLOYER COMPANY NAME",
"ACCOUNT DIRECTOR",
"ACCOUNT DIRECTOR EMAIL",
"ACCOUNT MANAGER",
"ACCOUNT MANAGER EMAIL",
"RECRUITER AGENCY NAME",
"RECRUITER EMAIL ADDRESS",
"POSTING CITIES",
"POSTING REGIONS",
"POSTING STATES",
"POSTING COUNTRIES",
"POSTING FULL LOCATIONS",
"SUBSCRIPTION TYPE",
"WORKER TYPE",
"EMPLOYER COUNTRY",
"EMPLOYER OFCCP STATUS",
"BUSINESS UNIT 2",
"JOB POSTING ID",
"CURRENCY_CONVERSION_DATE",
"CREATION_DATE" as "HIRE CREATION DATE",
"ADJUSTED_PAYMENT_STATUS"as "ADJUSTED PAYMENT STATUS",
"UNADJUSTED_PAYMENT_STATUS" as "UNADJUSTED PAYMENT STATUS",
"DIVERSITY STATUS" as "AGENCY DIVERSITY STATUS",
"POSTING FEE AMOUNT UNCONVERTED",
"RECRUITER COUNTRY",
"PAID_OUTSIDE" as "PAID OUTSIDE OF BOUNTYJOBS",
"CURRENCY_CONVERSION_RATE" as "CURRENCY CONVERSION RATE",
"EMPLOYER EMAIL",
"AWARD EMPLOYER NET",
"PAYMENT_DUE_DATE" as "PAYMENT DUE DATE",
"VENDOR_TYPE" as "HIRE VENDOR TYPE",
"posting user fullname" as "POSTING USER FULL NAME",
"POSTING USER FULLNAME1",
"POSTING USER EMAIL", 
"EMPLOYER COMPANY SIZE",
"RECRUITER AGENCY (FROM RA) - DO NOT USE",
"AWARD RESPONSE STATUS",
"PURCHASE_ORDER" as "PURCHASE ORDER" ,
"AWARD FEE AMOUNT",
"BOUNTYJOBS_ID",
"OFFER_ACCEPTED_DATE", 
"Invoice Added Date" as "HIRE INVOICE ADDED DATE",
"recruiter  last login" ,
"RECRUITER AGENCY ID",
"WORKFLOW_HANDLER_NAME" as "HIRE WORKFLOW HANDLER",
"POSTING BUSINESS UNIT 3",
"REVMOD" as "HIRE REVMOD CHECK",
"CONT HIRING MANAGER NAME",
"COST CENTER NUMBER",
"HIRING_MANAGER_NAME" as "HIRE HIRING MANAGER NAME",
"HIRING_MANAGER_EMAIL" as "HIRE HIRING MANAGER EMAIL",
"SUBMISSION TYPE",
"AWARD_ADDRESS_STATE" as "HIRE AWARD STATE",
"AWARD_ADDRESS_COUNTRY" as "HIRE AWARD COUNTRY"
from JoinData7Component
)
, DateOperationsNdCalculations as (
select 
    *,
    CASE 
        WHEN "HIRE SUBMISSION CREATED DATE" IS NULL OR "POSTING CREATION DATE" IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM ("HIRE SUBMISSION CREATED DATE"::timestamp - "POSTING CREATION DATE"::timestamp))::integer 
    END AS "HIRE TIME TO INBOX",   
    CASE 
        WHEN "HIRE CANDIDATE START DATE" IS NULL OR "POSTING CREATION DATE" IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM ("HIRE CANDIDATE START DATE"::timestamp - "POSTING CREATION DATE"::timestamp))::integer 
    END AS "HIRE TIME TO FILL ON START DATE",   
    CASE 
        WHEN "HIRE AWARD ACCEPTED DATE" IS NULL OR "POSTING CREATION DATE" IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM ("HIRE AWARD ACCEPTED DATE"::timestamp - "POSTING CREATION DATE"::timestamp))::integer 
    END AS "HIRE TIME TO FILL ON AWARD DATE",   
    CASE 
        WHEN "HIRE CANDIDATE START DATE" IS NULL OR "POSTING CREATION DATE" IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM ("HIRE CANDIDATE START DATE"::timestamp - "POSTING CREATION DATE"::timestamp))::integer 
    END AS "HIRE TIME TO START",
    CASE  
        WHEN "POSTING CREATION DATE" IS NULL OR "OFFER_ACCEPTED_DATE" IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM ("POSTING CREATION DATE"::timestamp - "OFFER_ACCEPTED_DATE"::timestamp))::integer 
    END AS "HIRE TIME TO OFFER ACCEPTED",
   CASE
        WHEN "HIRE AWARD UNCONVERTED" = 0 OR "HIRE AWARD UNCONVERTED" IS NULL THEN NULL
        ELSE "HIRE BOUNTYJOBS NET"/"HIRE AWARD UNCONVERTED" 
    END as "HIRE BOUNTYJOBS PERCENTAGE"
from SelectColumns 
)
,selectcolumns2 as (
select
*, 
"HIRE_ID" as "HIRE ID",
"OFFER_ACCEPTED_DATE" as "HIRE OFFER ACCEPTED DATE",
"CANDIDATE EMAIL" as "HIRE CANDIDATE EMAIL"
from DateOperationsNdCalculations
)
,HIRE_FILTERS as (
select
  *,
  "EMPLOYER COMPANY NAME" || ' (' || "POSTING BOUNTYJOBS ID"::text || ')' as "Company Filter",
    CASE 
        WHEN "POSTING YEARS EXPERIENCE" = 'Less than 1 year' THEN 1
        WHEN "POSTING YEARS EXPERIENCE" = '1+ to 2 years' THEN 2
        WHEN "POSTING YEARS EXPERIENCE" = '2+ to 5 years' THEN 3
        WHEN "POSTING YEARS EXPERIENCE" = '5+ to 7 years' THEN 4
        WHEN "POSTING YEARS EXPERIENCE" = '7+ to 10 years' THEN 5
        WHEN "POSTING YEARS EXPERIENCE" = '10+ to 15 years' THEN 6
        ELSE Null
    END as "Years of Experience Sort", 
    CASE 
        WHEN "POSTING COUNTRIES" LIKE '%United States%' THEN 'US' 
        WHEN "POSTING COUNTRIES" IS NULL AND "POSTING CURRENCY CODE" = 'USD' THEN 'US'
        WHEN "POSTING COUNTRIES" IS NULL AND "POSTING CURRENCY CODE" != 'USD' THEN 'International' 
        ELSE 'International' 
    END as "HIRE INTERNATIONAL",
    CASE 
        WHEN "ADJUSTED PAYMENT STATUS" = 'P' AND "HIRE PAYMENT ON TIME" = 1 THEN 'Paid - On Time' 
        WHEN "ADJUSTED PAYMENT STATUS" = 'P' AND "HIRE PAYMENT ON TIME" = 0 AND
        "HIRE LAST PAYMENT DATE" <= "HIRE CREATION DATE" THEN 'Paid - On Time' 
        WHEN "ADJUSTED PAYMENT STATUS" = 'P' AND
        "HIRE PAYMENT ON TIME" = 0 AND "HIRE LAST PAYMENT DATE" > "HIRE CREATION DATE" THEN 'Paid - Late' 
        WHEN "ADJUSTED PAYMENT STATUS" = 'R' THEN 'Refunded' 
        WHEN "ADJUSTED PAYMENT STATUS" = 'U' THEN 'Unpaid' 
        WHEN "ADJUSTED PAYMENT STATUS" = 'PP' THEN 'Partial Payment'
        ELSE "ADJUSTED PAYMENT STATUS"
    END as "ADJUSTED_PAYMENT_STATUS",
    CASE 
        WHEN "HIRE PLACEMENT TYPE" = 'Special Contract' THEN 'Preferred'
        WHEN "HIRE PLACEMENT TYPE" = 'Standard Terms' THEN 'Marketplace'
        WHEN "HIRE PLACEMENT TYPE" = 'Multi-fill Deal' THEN 'Marketplace' 
        ELSE "HIRE PLACEMENT TYPE" 
    END as "VENDOR TYPE",
    CASE 
        WHEN EXTRACT(MONTH FROM "HIRE CANDIDATE START DATE") IN (4,5,6,7,8,9,10,11,12) THEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE")
        WHEN EXTRACT(MONTH FROM "HIRE CANDIDATE START DATE") IN (1,2,3) THEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") - 1
    END as "FISCAL YEAR (4/1 - 3/31)",
    CASE 
        WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2) THEN EXTRACT(YEAR FROM CURRENT_DATE) - 3
        ELSE EXTRACT(YEAR FROM CURRENT_DATE) - 2
    END as "YEAR FILTER FOR CURRENT AND PRIOR FISCAL YEAR",
    CASE  
        WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = EXTRACT(YEAR FROM CURRENT_DATE) THEN 1 
        ELSE 0 
    END as "HIRE AWARD IS IN CURRENT CAL YEAR (NOTEBOOK FILTER)",
    CASE 
        WHEN "AWARD RESPONSE STATUS" = 'Pending' AND ("HIRE CANDIDATE START DATE" - CURRENT_DATE) < 0 THEN 1 
        ELSE 0 
    END as "PENDING AWARD WHERE CANDIDATE START DATE HAS PASSED",
    CASE 
        WHEN EXTRACT(MONTH FROM "HIRE CANDIDATE START DATE") IN (6,7,8,9,10,11,12) THEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE")
        WHEN EXTRACT(MONTH FROM "HIRE CANDIDATE START DATE") IN (1,2,3,4,5) THEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") - 1
    END as "FISCAL YEAR (6/1 - 5/31)",
    CASE 
        WHEN "HIRE TIME TO FILL ON START DATE" < 0 THEN 0 
        ELSE "HIRE TIME TO FILL ON START DATE" 
    END as "HIRE TIME TO FILL ON START_DATE",
    CASE 
        WHEN "HIRE VENDOR TYPE" = 1 THEN 'Preferred' 
        ELSE 'Marketplace' 
    END as "VENDOR CONTRACT TERMS"
from selectcolumns2
    )
,AddFormulas as (
select 
    *,
    CASE 
        WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2) THEN ("FISCAL YEAR (4/1 - 3/31)") - 1
        ELSE "FISCAL YEAR (4/1 - 3/31)"
    END as "CURRENT FISCAL YEAR (3/1 - 4/31)",    
    CASE 
        WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2) THEN ("FISCAL YEAR (4/1 - 3/31)") - 2
        ELSE ("FISCAL YEAR (4/1 - 3/31)") - 1 
    END as "PRIOR FISCAL YEAR (3/1 - 4/31)",    
    EXTRACT(YEAR FROM CURRENT_DATE) as "CURRENT CALENDAR YEAR",
    EXTRACT(YEAR FROM CURRENT_DATE) - 1 as "PRIOR CALENDAR YEAR",  
    CASE 
        WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2,3,4,5) THEN ("FISCAL YEAR (6/1 - 5/31)") - 1
        ELSE "FISCAL YEAR (6/1 - 5/31)"
    END as "CURRENT FISCAL YEAR (6/1 - 5/31)",
    CASE 
        WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2,3,4,5) THEN ("FISCAL YEAR (6/1 - 5/31)") - 2
        ELSE ("FISCAL YEAR (6/1 - 5/31)") - 1
    END as "PRIOR FISCAL YEAR (6/1 - 5/31)",
    "HIRE CANDIDATE START DATE"::date as "_PPT_FILTER_POSTING_AND_HIRE_DATE",
    "EMPLOYER COMPANY NAME" as "_PPT_FILTER_EMPLOYER_COMPANY",
  CASE 
    WHEN "POSTING FULL LOCATIONS" IS NULL THEN NULL
    ELSE TRIM(
        RIGHT(
            "POSTING FULL LOCATIONS",
            STRPOS(REVERSE("POSTING FULL LOCATIONS"), ',') - 1
        )
    )
END AS "POSTING FULL LOCATIONS SPLIT COUNTRY"
from HIRE_FILTERS
)
,check_FILTER_FOR_CUSTOM_FISCAL_YEARS as (
select
*,
CASE 
    WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2) THEN
        (CASE WHEN "FISCAL YEAR (4/1 - 3/31)" > "YEAR FILTER FOR CURRENT AND PRIOR FISCAL YEAR" 
              AND "FISCAL YEAR (4/1 - 3/31)" < EXTRACT(YEAR FROM CURRENT_DATE) 
         THEN 'YES' ELSE 'NO' END)
    ELSE 
        (CASE WHEN "FISCAL YEAR (4/1 - 3/31)" > "YEAR FILTER FOR CURRENT AND PRIOR FISCAL YEAR" 
         THEN 'YES' ELSE 'NO' END)
END as "IS CURRENT AND PRIOR FY (3/1 - 4/31)",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "PRIOR FISCAL YEAR (3/1 - 4/31)"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD PRIOR FISCAL YEAR (3/1 - 4/31)",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "CURRENT FISCAL YEAR (3/1 - 4/31)"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD CURRENT FISCAL YEAR (3/1 - 4/31)",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "CURRENT CALENDAR YEAR"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD CURRENT CALENDAR YEAR",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "PRIOR CALENDAR YEAR"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD PRIOR CALENDAR YEAR",
CASE 
    WHEN "EMPLOYER COMPANY ID" IN (68546,136228) AND "HIRE AWARD STATUS" = 'Final' 
    THEN 'OK TO SEND TO PHILIPS' 
    ELSE 'NO' 
END as "PHILIPS HIRE PROCESSED EMAIL FILTER",
CASE 
    WHEN EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2,3,4,5) THEN
        (CASE WHEN "FISCAL YEAR (6/1 - 5/31)" > "YEAR FILTER FOR CURRENT AND PRIOR FISCAL YEAR" 
              AND "FISCAL YEAR (6/1 - 5/31)" < EXTRACT(YEAR FROM CURRENT_DATE) 
         THEN 'YES' ELSE 'NO' END)
    ELSE 
        (CASE WHEN "FISCAL YEAR (6/1 - 5/31)" > "YEAR FILTER FOR CURRENT AND PRIOR FISCAL YEAR" 
         THEN 'YES' ELSE 'NO' END)
END as "IS CURRENT AND PRIOR FY (6/1 - 5/31)",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "PRIOR FISCAL YEAR (6/1 - 5/31)"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD PRIOR FISCAL YEAR (6/1 - 5/31)",
CASE 
    WHEN EXTRACT(YEAR FROM "HIRE CANDIDATE START DATE") = "CURRENT FISCAL YEAR (6/1 - 5/31)"
    THEN "HIRE AWARD" 
    ELSE 0 
END as "HIRE AWARD CURRENT FISCAL YEAR (6/1 - 5/31)"
from AddFormulas
)
,selectcolumns3 as (
select *
from check_FILTER_FOR_CUSTOM_FISCAL_YEARS 
)
,Executive_Segment_Output as (
select 
    CAST(NULL AS INTEGER) AS "EMPLOYER COMPANY ID",
    CAST(NULL AS TEXT) AS "EMPLOYER COMPANY NAME",
    CAST(NULL AS TEXT) AS "EXECUTIVE SEGMENT"
)
,Joindata6component as (
select 
sc3.*,
eso."EXECUTIVE SEGMENT"
from selectcolumns3 sc3
left outer join Executive_Segment_Output eso on sc3."EMPLOYER COMPANY ID"  = eso."EMPLOYER COMPANY ID"
)
,ZoomInfo_Lookup_output as (
select 
    CAST(NULL AS INTEGER) AS "company id",
    CAST(NULL AS TEXT) AS "company name",
    CAST(NULL AS TEXT) AS "hubspot industry",
    CAST(NULL AS TEXT) AS "zoominfo industry",
    CAST(NULL AS TEXT) AS "zoominfo sub-industry",
    CAST(NULL AS INTEGER) AS "rn"
)
,joindata8component as (
select jc6.*,
       zlo."hubspot industry" as "EMPLOYER HUBSPOT INDUSTRY",
       zlo."zoominfo industry" as "EMPLOYER ZOOMINFO INDUSTRY",
       zlo."zoominfo sub-industry" as "EMPLOYER ZOOMINFO SUB_INDUSTRY",
       zlo."company id",
       zlo."company name",
       zlo."rn"
from Joindata6component jc6 
left outer join ZoomInfo_Lookup_output zlo on jc6."EMPLOYER COMPANY ID" = zlo."company id" 
)
select
"HIRE ID",
"HIRE SUBMISSION ID",
"HIRE TIME TO OFFER ACCEPTED",
"HIRE OFFER ACCEPTED DATE",
"HIRE TIME TO START",
"CURRENCY CONVERSION RATE",
"EMPLOYER EMAIL",
"AWARD EMPLOYER NET",
"PAYMENT DUE DATE",
"HIRE VENDOR TYPE",
"VENDOR TYPE",
"FISCAL YEAR (4/1 - 3/31)",
"CURRENT FISCAL YEAR (3/1 - 4/31)",
"PRIOR FISCAL YEAR (3/1 - 4/31)",
"CURRENT CALENDAR YEAR",
"PRIOR CALENDAR YEAR",
"IS CURRENT AND PRIOR FY (3/1 - 4/31)",
"HIRE AWARD PRIOR FISCAL YEAR (3/1 - 4/31)",
"HIRE AWARD CURRENT FISCAL YEAR (3/1 - 4/31)",
"HIRE AWARD CURRENT CALENDAR YEAR",
"HIRE AWARD PRIOR CALENDAR YEAR",
"PHILIPS HIRE PROCESSED EMAIL FILTER",
"POSTING USER FULLNAME1" as "POSTING USER FULL NAME",
"POSTING USER EMAIL",
"EMPLOYER COMPANY SIZE",
"RECRUITER AGENCY (FROM RA) - DO NOT USE",
"HIRE AWARD IS IN CURRENT CAL YEAR (NOTEBOOK FILTER)",
"AWARD RESPONSE STATUS",
"PENDING AWARD WHERE CANDIDATE START DATE HAS PASSED",
"FISCAL YEAR (6/1 - 5/31)",
"CURRENT FISCAL YEAR (6/1 - 5/31)",
"PRIOR FISCAL YEAR (6/1 - 5/31)",
"IS CURRENT AND PRIOR FY (6/1 - 5/31)",
"HIRE AWARD PRIOR FISCAL YEAR (6/1 - 5/31)",
"HIRE AWARD CURRENT FISCAL YEAR (6/1 - 5/31)",
"AWARD FEE AMOUNT",
"BOUNTYJOBS_ID",
"_PPT_FILTER_POSTING_AND_HIRE_DATE",
"_PPT_FILTER_EMPLOYER_COMPANY",
"PURCHASE ORDER",
"VENDOR CONTRACT TERMS",
"HIRE INVOICE ADDED DATE",
"recruiter  last login" ,
"POSTING FULL LOCATIONS SPLIT COUNTRY",
"RECRUITER AGENCY ID",
"HIRE WORKFLOW HANDLER",
"POSTING BUSINESS UNIT 3",
"HIRE REVMOD CHECK",
"CONT HIRING MANAGER NAME",
"COST CENTER NUMBER",
"HIRE HIRING MANAGER NAME",
"HIRE HIRING MANAGER EMAIL",
"SUBMISSION TYPE",
"HIRE AWARD STATE",
"HIRE AWARD COUNTRY",
"EXECUTIVE SEGMENT",
"company id",
"company name",
"EMPLOYER HUBSPOT INDUSTRY",
"EMPLOYER ZOOMINFO INDUSTRY",
"EMPLOYER ZOOMINFO SUB_INDUSTRY",
"RN",
"ADJUSTED_PAYMENT_STATUS" as "ADJUSTED PAYMENT STATUS",
"UNADJUSTED PAYMENT STATUS",
"POSTING FEE AMOUNT UNCONVERTED",
"RECRUITER COUNTRY",
"AGENCY DIVERSITY STATUS",
"PAID OUTSIDE OF BOUNTYJOBS",
"HIRE INTERNATIONAL",
"POSTING BOUNTYJOBS ID",
"HIRE SUBMISSION CREATED BY",
"HIRE SUBMISSION CREATED DATE",
"HIRE SUBMISSION COMPENSATION OWNER",
"HIRE CURRENCY CODE",
"HIRE SALARY PERCENT AWARD",
"HIRE AWARD",
"HIRE AWARD UNCONVERTED",
"HIRE SALARY",
"HIRE SALARY UNCONVERTED",
"HIRE CANDIDATE START DATE",
"HIRE PURCHASE ORDER",
"HIRE PAYMENT STATUS",
"HIRE INVOICE NUMBER",
"HIRE PAYMENT DATE",
"HIRE PAYMENT CREATOR ID",
"HIRE PAYMENT MODIFIER ID",
"HIRE AWARD STATUS",
"HIRE PAYMENT MODIFICATION DATE",
"HIRE LAST PAYMENT DATE",
"HIRE PAYMENT ON TIME",
"HIRE PLACEMENT TYPE",
"HIRE TIME TO INBOX",
"HIRE BOUNTYJOBS NET",
"HIRE BOUNTYJOBS NET UNCONVERTED",
"HIRE BOUNTYJOBS PERCENTAGE",
"HIRE RECRUITER NET",
"HIRE AWARD ACCEPTOR",
"HIRE RECRUITER NET UNCONVERTED",
"HIRE EMPLOYER NET",
"HIRE EMPLOYER NET UNCONVERTED",
"HIRE TIME TO FILL ON AWARD DATE",
"RECRUITER FULL NAME",
"HIRE AWARD ACCEPTED DATE",
"HIRE TIME TO FILL ON START_DATE" as "HIRE TIME TO FILL ON START DATE",
"SUBMISSION STATUS",
"POSTING CREATION DATE",
"POSTING TITLE",
"POSTING STATUS",
"RECRUITER USER ID",
"CANDIDATE ID",
"CANDIDATE FULL NAME",
"CANDIDATE TITLE",
"POSTING PRODUCT",
"POSTING SOURCE CHANNEL",
"POSTING SOURCE DETAIL",
"POSTING EXTERNAL ID",
"POSTING USER ID",
"POSTING USER FULLNAME",
"POSTING COSOURCE CLIENT NAME",
"POSTING NUMBER OF POSITIONS",
"POSTING BUSINESS UNIT",
"POSTING INDUSTRY PARENT",
"POSTING INDUSTRY CHILD",
"POSTING JOB CATEGORY PARENT",
"POSTING JOB CATEGORY CHILD",
"POSTING FEE MODEL",
"POSTING FEE TYPE",
"POSTING FEE PERCENTAGE",
"POSTING CURRENCY CODE",
"POSTING FEE AMOUNT",
"POSTING SALARY MINIMUM RANGE",
"POSTING SALARY MAXIMUM RANGE",
"POSTING BONUS ELIGIBLE",
"POSTING BONUS MINIMUM RANGE",
"POSTING BONUS MAXIMUM RANGE",
"POSTING COMMISSION ELIGIBLE",
"POSTING OVERTIME ELIGIBLE",
"POSTING EMPLOYMENT TYPE",
"POSTING HOURS PER WEEK",
"POSTING BENEFITS",
"POSTING INTERVIEW REIMBURSED",
"POSTING RELOCATION ASSISTANCE",
"POSTING OFFCCP COMPLIANCE",
"POSTING REMOTE POSITION",
"POSTING EDUCATION LEVEL",
"POSTING YEARS EXPERIENCE",
"POSTING SENIORITY",
"POSTING MANAGEMENT EXPERIENCE",
"POSTING VISA CANDIDATES CONSIDERED",
"POSTING SECURITY CLEARANCE REQUIRED",
"POSTING TRAVEL REQUIREMENTS",
"POSTING VISIBILITY",
"POSTING PRIORITY",
"POSTING REPOST TYPE",
"EMPLOYER PAYMENT TERMS",
"POSTING INTAKE SESSION STATUS",
"POSTING INTAKE SESSION DATETIME",
"HIRE CANDIDATE EMAIL",
"EMPLOYER COMPANY ID",
"EMPLOYER COMPANY NAME",
"ACCOUNT DIRECTOR",
"ACCOUNT DIRECTOR EMAIL",
"ACCOUNT MANAGER",
"ACCOUNT MANAGER EMAIL",
"RECRUITER AGENCY NAME",
"RECRUITER EMAIL ADDRESS",
"POSTING CITIES",
"POSTING REGIONS",
"POSTING STATES",
"POSTING COUNTRIES",
"POSTING FULL LOCATIONS",
"WORKER TYPE",
"SUBSCRIPTION TYPE",
"EMPLOYER COUNTRY",
"EMPLOYER OFCCP STATUS",
"BUSINESS UNIT 2",
"JOB POSTING ID",
"CURRENCY_CONVERSION_DATE",
"HIRE CREATION DATE",
"Company Filter",
"Years of Experience Sort"
from joindata8component