-- Data Source : BountyJobs | SQL | Employer User
-- https://bountyjobs.domo.com/datasources/5a537557-35d5-42ab-aa8e-6748cd9a335e/details/overview
SELECT
       PT.PARTY_ID,
       PT.CURRENCY_CODE,
       REFS.DESCRIPTION AS REFERRER_STATUS,
       MKTQ.DESCRIPTION AS MARKETING_QUESTION,
       NP.DESCRIPTION AS NAME_PREFIX,
       PST.DESCRIPTION AS USER_STATUS,
       PN.COMPANY_ID,
       C.NAME AS COMPANY_NAME,
       CASE WHEN PN.EMAIL_CONFIRMED = 'Y' THEN TRUE ELSE FALSE END AS EMAIL_CONFIRMED,
       PN.FIRST_NAME AS FIRST_NAMES,
       PN.LAST_NAME,
       PN.EMAIL_ADDRESS,
       PN.PHONE,
       PN.MOBILE_PHONE,
       PN.CREATED_BY,
       PN.CREATION_DATE,
       PN.MODIFIED_BY,
       PN.MODIFIED_DATE,
       PN.LAST_LOGIN,
       DATEDIFF(day, PN.LAST_LOGIN, GETDATE()) AS DAYS_SINCE_LAST_LOGIN,
       CASE 
    	WHEN (
        	SELECT COUNT(*) 
        	FROM bounty_jobs.email_suppression_list ESL 
        	WHERE ESL.EMAIL = PN.EMAIL_ADDRESS 
          		AND ACTIVE = 1
    		) >= 1 THEN 1
    		ELSE 0
		END AS ACTIVE_EMAIL_SUPPRESSED,
		CASE 
    		WHEN DATEDIFF(day, PN.LAST_LOGIN, GETDATE()) > 90 THEN 
        		CASE 
            		WHEN EXISTS (
                		SELECT 1 
                		FROM bounty_jobs.email_suppression_list ESL 
                		WHERE ESL.EMAIL = PN.EMAIL_ADDRESS 
                  		AND ACTIVE = 1
            		) THEN 1
            		ELSE 0
        		END
    		ELSE 0
END 		AS USER_SUPPRESSION_INTEGRATION,
--       IF ((SELECT COUNT(*) FROM bounty_jobs.email_suppression_list ESL WHERE ESL.EMAIL = PN.EMAIL_ADDRESS AND ACTIVE = 1) >= 1, 1, 0) AS ACTIVE_EMAIL_SUPPRESSED,
--       IF (DATEDIFF(NOW(), PN.LAST_LOGIN) > 90, IF ((SELECT COUNT(*) FROM bounty_jobs.email_suppression_list ESL WHERE ESL.EMAIL = PN.EMAIL_ADDRESS AND ACTIVE = 1) >= 1, 1, 0), 0) AS USER_SUPPRESSION_INTEGRATION,
       PN.FAX,
       CASE WHEN PN.ACCEPT_TERMS = 'Y' THEN TRUE ELSE FALSE END AS TERMS_ACCEPTED,
       PN.HIRING_MANAGER_REFERRAL_CODE AS REFERRAL_CODE,
       PN.PHONE_EXTENSION,
       PN.FAX_EXTENSION,
       CASE WHEN PN.PROFILE_COMPLETE = 'Y' THEN TRUE ELSE FALSE END AS PROFILE_COMPLETE,
       PN.INITIAL_ACTIVATION_DATE, -- first post date
       PN.REFERRAL_PROGRAM_ID,
       CASE WHEN PN.PHONE_PRIVATE_FLAG = 'Y' THEN TRUE ELSE FALSE END AS PHONE_PRIVATE,
       CASE WHEN PN.BOUNTY_JOBS_CERTIFIED_FLAG = 'Y' THEN TRUE ELSE FALSE END AS BOUNTYJOBS_CERTIFIED,  -- possibly ignorable
       RMKTS.DESCRIPTION AS REFERRER_MARKETING_STATUS,
       CASE WHEN PN.BJ_REPORT_FLAG = 'Y' THEN TRUE ELSE FALSE END AS BOUNTYJOBS_REPORT,
       CASE WHEN PN.BJ_REPORT_ADMIN_FLAG = 'Y' THEN TRUE ELSE FALSE END AS BOUNTYJOBS_REPORT_ADMIN,
       PN.MARKETING_QUESTION_DETAILS,
       CASE WHEN PN.FIRST_LOGIN_FLAG = 'Y' THEN TRUE ELSE FALSE END AS FIRST_LOGIN,
       PN.WORKFLOW_HANDLER_NAME AS USER_HANDLER_NAME,
       HM.INDUSTRY_ID_1,
       HM.INDUSTRY_ID_2,
       HM.INDUSTRY_ID_3,
       CS.DESCRIPTION AS COMPANY_SIZE,
       HM.BILLING_CONTACT_EMAIL,
       HM.BILLING_CONTACT_NAME,
       HM.BILLING_CONTACT_PHONE,
       HM.BILLING_CONTACT_PHONE_EXTENSION,
       HM.BUSINESS_UNIT,
       HM.JOB_TITLE,
       CI.DESCRIPTION AS COMPANY_IDENTITY,
       HM.PUBLIC_DISPLAY_DESCRIPTION,
       HM.FILLS_EARNED_FOR_PRIORITY_POSTING,
       HM.PRIORITY_POSTINGS_AVAILABLE,
       CASE WHEN HM.EARNS_PRIORITY_POSTINGS_FLAG = 'Y' THEN TRUE ELSE FALSE END AS EARNS_PRIORITY_POSTINGS,
       CASE WHEN HM.DIRECT_HIRE_BOUNTY_ALLOWED_FLAG = 'Y' THEN TRUE ELSE FALSE END AS DIRECT_HIRE_BOUNTY_ALLOWED,
       CASE
           WHEN HM.RETAINED_BOUNTY_ALLOWED_FLAG = 'Y'
               AND HM.DIRECT_HIRE_BOUNTY_ALLOWED_FLAG = 'Y'
               AND C.RETAINED_ALLOWED_FLAG = 'Y'
               THEN TRUE
           ELSE FALSE END AS RETAINED_BOUNTY_ALLOWED,
       CASE
           WHEN HM.CONTINGENT_BOUNTY_ALLOWED_FLAG = 'Y'
               AND (SELECT COUNT(*)
                    FROM bounty_jobs.contract_posting_configuration CPC
                             JOIN bounty_jobs.contract_posting_vendor CPV ON CPC.CONTRACT_POSTING_VENDOR_ID = CPV.ID
                    WHERE CPC.COMPANY_ID = C.COMPANY_ID
                      AND CPC.ACTIVE = 1
                      AND CPV.ACTIVE = 1) > 0
               THEN TRUE
           ELSE FALSE END AS CONTINGENT_BOUNTY_ALLOWED,
       A.ADDRESS_1,
       A.ADDRESS_2,
       A.POSTAL_CODE,
       A.CITY,
       A.STATE,
       A.COUNTRY,
       COP.EMAIL_ADDRESS AS COMPENSATION_OWNER_EMAIL,
       COALESCE(COP.FIRST_NAME, '') || ' ' || COALESCE(COP.LAST_NAME, '') AS COMPENSATION_OWNER_NAME,
       AMG.EMAIL_ADDRESS AS ACCOUNT_MANAGER_EMAIL,
       COALESCE(AMG.FIRST_NAME, '') || ' ' || COALESCE(AMG.LAST_NAME, '') AS ACCOUNT_MANAGER_NAME,
       (
          SELECT SPIN.RECRUITER_ID
             FROM bounty_jobs.split_poster SPIN
             WHERE SPIN.HIRING_MANAGER_ID = HM.PERSON_ID
       ) AS COSOURCE_RECRUITER_ID,
       CASE WHEN PN.INTERNAL_USER_FLAG = 'Y' THEN TRUE ELSE FALSE END AS INTERNAL_USER,
       HM.DOMO_EMAIL_RECIPIENT,
       CASE WHEN R.RELATIONSHIP_ID IS NULL THEN 'Standard' ELSE 'Admin' END AS "User Type",
       CASE WHEN PN.PROFILE_COMPLETE = 'Y' THEN TRUE ELSE FALSE END AS PROFILE_COMPLETE
FROM bounty_jobs.party PT
       JOIN bounty_jobs.person PN ON PT.PARTY_ID = PN.PERSON_ID
       JOIN bounty_jobs.hiring_manager HM on PN.PERSON_ID = HM.PERSON_ID
       LEFT JOIN bounty_jobs.referrer_status REFS ON REFS.CODE = PN.REFERRER_STATUS_CODE
       LEFT JOIN bounty_jobs.marketing_question MKTQ on PN.MARKETING_QUESTION_CODE = MKTQ.CODE
       LEFT JOIN bounty_jobs.name_prefix NP on PN.NAME_PREFIX_CODE = NP.CODE
       LEFT JOIN bounty_jobs.person_status PST ON PN.PERSON_STATUS_CODE = PST.CODE
       LEFT JOIN bounty_jobs.referrer_marketing_status RMKTS on PN.REFERRER_MARKETING_STATUS_CODE = RMKTS.CODE
       LEFT JOIN bounty_jobs.company_size CS ON CS.ID = HM.COMPANY_SIZE_ID
       LEFT JOIN bounty_jobs.company_identity CI on HM.COMPANY_IDENTITY_CODE = CI.CODE
       LEFT JOIN bounty_jobs.address A on PT.PARTY_ID = A.PARTY_ID AND A.ADDRESS_TYPE_CODE = 'PR'
       LEFT JOIN bounty_jobs.company C on PN.COMPANY_ID = C.COMPANY_ID
       LEFT JOIN bounty_jobs.person COP ON C.COMP_OWNER_ID = COP.PERSON_ID
       LEFT JOIN bounty_jobs.person AMG ON C.ACT_MGR_ID = AMG.PERSON_ID
       LEFT JOIN bounty_jobs.relationship R ON R.SOURCE_PARTY_ID = PN.PERSON_ID AND R.TARGET_PARTY_ID = PN.COMPANY_ID AND R.RELATIONSHIP_TYPE_CODE IN ('CA') AND R.RECORD_STATUS_CODE = 'A' 
limit 10;
       
       