SELECT ID,NAME,PARENT_ID,PARENT_NAME,TOP_DISPLAY_NAME AS PARENT_INDUSTRY,
CASE
    WHEN PARENT_ID = 1 THEN 'None Selected'
    ELSE NAME
END AS CHILD_INDUSTRY
FROM dbt_noumanjilani.bountyjobs_sql_industry