-- BountyJobs | SQL | Employer Company
-- https://bountyjobs.domo.com/datasources/e1d74a68-cef5-4e5c-be66-669a38636b22/details/overview
-- used in workflow Employer : https://bountyjobs.domo.com/datasources/6de36b60-3b51-40e0-adb0-6916f61b80a6/details/overview
select
	C.COMPANY_ID,
	C.NAME,
	C.DESCRIPTION,
	(CASE WHEN C.EXTEND_CREDIT_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS EXTEND_CREDIT,
	C.CREATION_DATE,
	C.CREATED_BY,
	C.MODIFIED_BY,
	C.MODIFIED_DATE,
	C.COMPANY_WEBSITE,
	PCS.DESCRIPTION AS POSTING_CREDIT_STATUS,
	OS.DESCRIPTION AS OFCCP_STATUS,
	(CASE WHEN C.ENTERPRISE_ACCOUNT_HOLDER = 'Y' THEN TRUE ELSE FALSE END) AS ENTERPRISE,
	(CASE WHEN C.PRIVATE_BOUNTIES_ALLOWED = 'Y' THEN TRUE ELSE FALSE END) AS PRIVATE_BOUNTIES_ALLOWED,
	(CASE WHEN C.POSTING_REPOST_CONFIGURABLE = 'Y' THEN TRUE ELSE FALSE END) AS POSTING_REPOST_CONFIGURABLE,
	(CASE WHEN C.FLAT_FEE_BOUNTY_ALLOWED_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS FLAT_FEE_ALLOWED,
	(CASE WHEN C.UNLIMITED_ENTERPRISE_USERS_ALLOWED_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS UNLIMITED_ENTERPRISE_USERS_ALLOWED,
	C.PAYMENT_TERM,
	C.LEGAL_COMPANY_NAME,
	C.PARENT_ID AS COMPANY_PARENT_ID,
	(CASE WHEN C.CUSTOM_CONTRACT_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS CUSTOM_CONTRACT,
	C.LAUNCH_DATE,
	DST.DESCRIPTION AS DUPLICATION_SUBMISSION_TYPE,
	C.POSTING_ALLOWED,
	C.POSTING_ALLOWED_CONTINGENT,
	(CASE WHEN C.RETAINED_ALLOWED_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS RETAINED_ALLOWED,
	(CASE WHEN C.COMPENSATION_HISTORY_ALLOWED = 'Y' THEN TRUE ELSE FALSE END) AS COMPENSATION_HISTORY_ALLOWED,
	C.WORKFLOW_HANDLER_NAME AS COMPANY_HANDLER,
	AC.NAME AS ATS_VENDOR,
	A.DRAFT_ONLY AS ATS_DRAFT_ONLY,
	(
	SELECT SAT_IN.DESCRIPTION
	FROM {{ source('bounty_jobs', 'SPECIAL_AGREEMENT_TERM') }} SAT_IN
	WHERE SAT_IN.COMPANY_ID = C.COMPANY_ID
	  AND SAT_IN.DEFAULT_TERM = 'Y'
	ORDER BY SAT_IN.CREATION_DATE DESC
	LIMIT 1
	) AS SPECIAL_CONTRACT_TERM,
	(CASE 
		WHEN REL.SOURCE_PARTY_ID IS NOT NULL THEN REL.SOURCE_PARTY_ID
		ELSE (SELECT MIN(PIN.PERSON_ID) FROM {{ source('bounty_jobs', 'PERSON') }} PIN WHERE PIN.COMPANY_ID = C.COMPANY_ID AND PIN.PERSON_STATUS_CODE = 'A')
	END) AS MASTER_EMPLOYER_ID,
	(CASE 
		WHEN REL.SOURCE_PARTY_ID IS NOT NULL THEN MASTER.RECRUITER_REFERRAL_CODE
		ELSE (SELECT PIN.RECRUITER_REFERRAL_CODE FROM {{ source('bounty_jobs', 'PERSON') }} PIN WHERE PIN.COMPANY_ID = C.COMPANY_ID ORDER BY PIN.PERSON_ID LIMIT 1)
	END) AS REFERRAL_CODE,
	C.INTEGRATION_SUPPRESSION,
	C.COMP_OWNER_ID,
	C.ACT_MGR_ID,
	CNTRNAME.ALLOWED_POSTING_COUNTRIES,
    CNTRGRPNAME.ALLOWED_POSTING_GROUPS,
       C.RETAINED_GROSS_UP_FLAG
FROM 
	{{ source('bounty_jobs', 'COMPANY') }} C
	LEFT JOIN {{ source('bounty_jobs', 'POSTING_CREDIT_STATUS') }} PCS on C.POSTING_CREDIT_STATUS_CODE = PCS.CODE
	LEFT JOIN {{ source('bounty_jobs', 'OFCCP_STATUS') }} OS on C.OFCCP_STATUS_CODE = OS.CODE
	LEFT JOIN {{ source('bounty_jobs', 'W9_TYPE') }} W9T ON C.W9_TYPE_CODE = W9T.CODE
	LEFT JOIN {{ source('bounty_jobs', 'CONTRACT_TYPE') }} CT on C.CONTRACT_TYPE_CODE = CT.CODE
	LEFT JOIN {{ source('bounty_jobs', 'COMPANY_LEGAL_STATUS_TYPE') }} CLST on C.COMPANY_LEGAL_STATUS_TYPE_CODE = CLST.CODE
	LEFT JOIN {{ source('bounty_jobs', 'DUPLICATE_SUBMISSION_TYPE') }} DST on C.DUPLICATE_SUBMISSION_TYPE = DST.CODE
	LEFT JOIN {{ source('bounty_jobs', 'ATS') }} A ON A.COMPANY_ID = C.COMPANY_ID
	LEFT JOIN {{ source('bounty_jobs', 'ATS_COMPANY') }} AC ON A.ATS_COMPANY_ID = AC.ATS_COMPANY_ID
	LEFT JOIN 
		(
		SELECT 
			RELX.SOURCE_PARTY_ID, 
			RELX.TARGET_PARTY_ID
		FROM 
			{{ source('bounty_jobs', 'RELATIONSHIP') }} RELX
			JOIN {{ source('bounty_jobs', 'PERSON') }} PXIN ON PXIN.PERSON_ID = RELX.SOURCE_PARTY_ID
		WHERE 
			RELX.RELATIONSHIP_TYPE_CODE = 'CM'
			AND PXIN.PERSON_STATUS_CODE = 'A'
		ORDER BY 
			RELX.CREATION_DATE DESC
		LIMIT 1
		) REL ON REL.TARGET_PARTY_ID = C.COMPANY_ID
	LEFT JOIN {{ source('bounty_jobs', 'PERSON') }} MASTER ON REL.SOURCE_PARTY_ID = MASTER.PERSON_ID
	LEFT JOIN 
		(
		SELECT 
			CCH.COMPANY_ID,
           	 	LISTAGG(CGRO.GROUP_NAME, ', ') WITHIN GROUP (ORDER BY CGRO.GROUP_NAME) AS ALLOWED_POSTING_GROUPS
		FROM 
			{{ source('bounty_jobs', 'COMPANY_COUNTRY_GROUP') }} CCH
			JOIN {{ source('bounty_jobs', 'GROUPED_COUNTRY') }} CG ON CG.GROUP_ID = CCH.COUNTRY_GROUP_ID
			JOIN {{ source('bounty_jobs', 'REGION_COUNTRY_INFO') }} RCI ON RCI.ISO_ALPHA2 = CG.COUNTRY_CODE
            		LEFT JOIN {{ source('bounty_jobs', 'COUNTRY_GROUP') }} CGRO ON CCH.COUNTRY_GROUP_ID = CGRO.ID
		GROUP BY 
			CCH.COMPANY_ID
		) CNTRGRPNAME ON C.COMPANY_ID = CNTRGRPNAME.COMPANY_ID
		LEFT JOIN 
		(
		SELECT 
			CCH.COMPANY_ID,
				LISTAGG(RCI.NAME, ' ') WITHIN GROUP (ORDER BY RCI.NAME) AS ALLOWED_POSTING_COUNTRIES
		FROM 
			{{ source('bounty_jobs', 'COMPANY_COUNTRY_GROUP') }} CCH
			JOIN {{ source('bounty_jobs', 'GROUPED_COUNTRY') }} CG ON CG.GROUP_ID = CCH.COUNTRY_GROUP_ID
			JOIN {{ source('bounty_jobs', 'REGION_COUNTRY_INFO') }} RCI ON RCI.ISO_ALPHA2 = CG.COUNTRY_CODE
            		LEFT JOIN {{ source('bounty_jobs', 'COUNTRY_GROUP') }} CGRO ON CCH.COUNTRY_GROUP_ID = CGRO.ID
		GROUP BY 
			CCH.COMPANY_ID
		) CNTRNAME ON C.COMPANY_ID = CNTRNAME.COMPANY_ID
WHERE 
	C.COMPANY_TYPE_CODE = 'E'