--Ready Contractor Assignment
-- https://bountyjobs.domo.com/datacenter/dataflows/198/graph
with staffing_assignment as(
SELECT
    CPSA.ID AS ASSIGNMENT_ID,
    CPSA.SUBMISSION_ID,
    CPAS.STATUS_NAME AS ASSIGNMENT_STATUS,
    CPAS.IS_ACTIVE AS ACTIVE,
    CPAS.IS_HIRED AS HIRED,
    CPSA.STAFFING_AWARD_MESSAGE_ID,
    CPSA.CREATED_BY,
    CPSA.CREATION_DATE,
    CPSA.MODIFIED_BY,
    CPSA.MODIFIED_DATE,
    CPSA.BUSINESS_UNIT,
    CPSA.HIRING_MANAGER_NAME,
    CPSA.HIRING_MANAGER_EMAIL,
    CPSA.HIRING_MANAGER_PHONE,
    CPSA.HIRING_MANAGER_ROLE,
    CPSA.TIME_APPROVER_NAME,
    CPSA.TIME_APPROVER_EMAIL,
    CPSA.TIME_APPROVER_PHONE,
    CPSA.CONTRACT_BEGIN_DATE AS START_DATE,
    CPSA.CONTRACT_END_DATE AS END_DATE,
    CPSA.BILL_RATE_MAXIMUM AS BILL_RATE,
    CPSA.PAY_RATE_MAXIMUM AS PAY_RATE,
    CPSA.EMPLOYEE_TYPE AS WORKER_TYPE,
    CC.NAME,
    CPV.ID AS EOR_ID,
    CPSA.REFERENCE_ID as WORKER_ID
FROM bounty_jobs.contract_posting_submission_assignment CPSA
         JOIN bounty_jobs.contract_posting_assignment_status CPAS ON CPSA.ASSIGNMENT_STATUS_ID = CPAS.ID
         LEFT JOIN bounty_jobs.contract_posting_vendor CPV ON CPV.ID = CPSA.CONTRACT_POSTING_VENDOR_ID
         LEFT JOIN bounty_jobs.company CC ON CC.COMPANY_ID = CPV.COMPANY_ID
        order by 1
)
select 
ASSIGNMENT_ID as "ASSIGNMENT ID",
SUBMISSION_ID as "WORKER SUBMISSION ID",
ASSIGNMENT_STATUS as "WORKER ASSIGNMENT STATUS",
ACTIVE,
HIRED,
STAFFING_AWARD_MESSAGE_ID as "STAFFING ASSIGNMENT AWARD MESSAGE ID",
CREATED_BY as "STAFFING ASSIGNMENT CREATED BY",
CREATION_DATE as "STAFFING ASSIGNMENT CREATION DATE",
MODIFIED_BY as "STAFFING ASSIGNMENT MODIFIED BY",
MODIFIED_DATE as "STAFFING ASSIGNMENT MODIFIED DATE",
BUSINESS_UNIT as "STAFFING ASSIGNMENT BUSINESS UNIT",
HIRING_MANAGER_NAME as "STAFFING ASSIGNMENT HIRING MANAGER NAME",
HIRING_MANAGER_EMAIL as "STAFFING ASSIGNMENT HIRING MANAGER EMAIL",
HIRING_MANAGER_PHONE as "STAFFING ASSIGNMENT HIRING MANAGER PHONE",
HIRING_MANAGER_ROLE as "STAFFING ASSIGNMENT HIRING MANAGER ROLE",
TIME_APPROVER_NAME as "STAFFING ASSIGNMENT TIME APPROVER NAME",
TIME_APPROVER_EMAIL as "STAFFING ASSIGNMENT TIME APPROVER EMAIL",
TIME_APPROVER_PHONE as "STAFFING ASSIGNMENT TIME APPROVER PHONE",
START_DATE as "STAFFING ASSIGNMENT START DATE",
END_DATE as "STAFFING ASSIGNMENT END DATE",
BILL_RATE as "WORKER BIILL RATE",
PAY_RATE as "WORKER PAY RATE",
WORKER_TYPE as "WORKER TYPE",
NAME as "EOR NAME"
from staffing_assignment

