--STAFFING_ASSIGNMENT
--https://bountyjobs.domo.com/datasources/92681a8c-9316-426e-80da-e9d3d8da9755/details/settings
SELECT
    CPSA.ID AS ASSIGNMENT_ID,
    CPSA.SUBMISSION_ID,
    CPAS.STATUS_NAME AS ASSIGNMENT_STATUS,
    CPAS.IS_ACTIVE AS ACTIVE,
    CPAS.IS_HIRED AS HIRED,
    CPSA.STAFFING_AWARD_MESSAGE_ID,
    CPSA.CREATED_BY,
    CPSA.CREATION_DATE,
    CPSA.MODIFIED_BY,
    CPSA.MODIFIED_DATE,
    CPSA.BUSINESS_UNIT,
    CPSA.HIRING_MANAGER_NAME,
    CPSA.HIRING_MANAGER_EMAIL,
    CPSA.HIRING_MANAGER_PHONE,
    CPSA.HIRING_MANAGER_ROLE,
    CPSA.TIME_APPROVER_NAME,
    CPSA.TIME_APPROVER_EMAIL,
    CPSA.TIME_APPROVER_PHONE,
    CPSA.CONTRACT_BEGIN_DATE AS START_DATE,
    CPSA.CONTRACT_END_DATE AS END_DATE,
    CPSA.BILL_RATE_MAXIMUM AS BILL_RATE,
    CPSA.PAY_RATE_MAXIMUM AS PAY_RATE,
    CPSA.EMPLOYEE_TYPE AS WORKER_TYPE,
    CC.NAME,
    CPV.ID AS EOR_ID,
    CPSA.REFERENCE_ID as WORKER_ID
FROM bounty_jobs.contract_posting_submission_assignment CPSA
         JOIN bounty_jobs.contract_posting_assignment_status CPAS ON CPSA.ASSIGNMENT_STATUS_ID = CPAS.ID
         LEFT JOIN bounty_jobs.contract_posting_vendor CPV ON CPV.ID = CPSA.CONTRACT_POSTING_VENDOR_ID
         LEFT JOIN bounty_jobs.company CC ON CC.COMPANY_ID = CPV.COMPANY_ID
        order by 1