-- Custom SQL
with rs_name as (SELECT 
		C.NAME,
		RS.REFERREE_ID
	FROM 
		{{ source('bounty_jobs', 'referral_slot') }} RS
		JOIN {{ source('bounty_jobs', 'person') }} P2 ON P2.PERSON_ID = RS.REFERRER_ID
		JOIN {{ source('bounty_jobs', 'company') }} C ON C.COMPANY_ID = P2.COMPANY_ID AND C.COMPANY_TYPE_CODE = 'E'
)
SELECT
DISTINCT	PT.PARTY_ID,
	PT.CURRENCY_CODE,
	REFS.DESCRIPTION AS REFERRER_STATUS,
	MKTQ.DESCRIPTION AS MARKETING_QUESTION,
	NP.DESCRIPTION AS NAME_PREFIX,
	PST.DESCRIPTION AS USER_STATUS,
	PN.COMPANY_ID,
	C.NAME,
	(CASE WHEN PN.EMAIL_CONFIRMED = 'Y' THEN TRUE ELSE FALSE END) AS EMAIL_CONFIRMED,
	PN.FIRST_NAME AS FIRST_NAMES,
	PN.LAST_NAME,
	PN.EMAIL_ADDRESS,
	PN.PHONE,
	PN.MOBILE_PHONE,
	PN.CREATED_BY,
	PN.CREATION_DATE,
	PN.MODIFIED_BY,
	PN.MODIFIED_DATE,
	PN.LAST_LOGIN,
	DATEDIFF(DAYS, PN.LAST_LOGIN, CURRENT_DATE) AS DAYS_SINCE_LAST_LOGIN,
    CASE 
        WHEN EXISTS (
            SELECT 1
            FROM {{ source('bounty_jobs', 'email_suppression_list') }} ESL 
            WHERE ESL.EMAIL = PN.EMAIL_ADDRESS 
            AND ESL.ACTIVE = 1
        ) THEN 1 
        ELSE 0 
    END AS ACTIVE_EMAIL_SUPPRESSED,
	 CASE
        WHEN DATEDIFF(DAYS, CURRENT_DATE, PN.LAST_LOGIN) > 90 THEN 
            CASE
                WHEN EXISTS (
                    SELECT 1 
                    FROM {{ source('bounty_jobs', 'email_suppression_list') }} ESL
                    WHERE ESL.EMAIL = PN.EMAIL_ADDRESS
                    AND ESL.ACTIVE = 1
                ) THEN 1
                ELSE 0
            END
        ELSE 0
    END AS USER_SUPPRESSION_INTEGRATION,
	PN.FAX,
	(CASE WHEN PN.ACCEPT_TERMS = 'Y' THEN TRUE ELSE FALSE END) AS TERMS_ACCEPTED,
	PN.PHONE_EXTENSION,
	PN.FAX_EXTENSION,
	(CASE WHEN PN.PROFILE_COMPLETE = 'Y' THEN TRUE ELSE FALSE END) AS PROFILE_COMPLETE,
	PN.REFERRAL_PROGRAM_ID,(CASE WHEN PN.PHONE_PRIVATE_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS PHONE_PRIVATE,
	(CASE WHEN PN.BOUNTY_JOBS_CERTIFIED_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS BOUNTYJOBS_CERTIFIED,
	RMKTS.DESCRIPTION AS REFERRER_MARKETING_STATUS,
	(CASE WHEN PN.BJ_REPORT_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS BOUNTYJOBS_REPORT,
	(CASE WHEN PN.BJ_REPORT_ADMIN_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS BOUNTYJOBS_REPORT_ADMIN,
	PN.MARKETING_QUESTION_DETAILS,
	(CASE WHEN PN.FIRST_LOGIN_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS FIRST_LOGIN,
	PN.WORKFLOW_HANDLER_NAME AS USER_HANDLER_NAME,EL.DESCRIPTION AS EDUCATION_LEVEL,
	C1.DESCRIPTION AS CERTIFICATION_1,
	C2.DESCRIPTION AS CERTIFICATION_2,
	C3.DESCRIPTION AS CERTIFICATION_3,
	R.SCHOOLS_ATTENDED,
	R.YEARS_RECRUITING,
	R.PERSONAL_DESCRIPTION,
	(CASE WHEN R.FLIERS_ALLOWED_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS FLIERS_ALLOWED,
	R.MAX_ENGAGEMENT_SLOTS,
	R.MEMBERSHIPS,
	R.LEGAL_FIRST_NAME,
	R.LEGAL_LAST_NAME,
	R.ROLE_WITHIN_ORG,
	R.MEANS_OF_SOURCING,
	R.ONLINE_RESOURCES_FOR_SOURCING,
	R.COMPANIES_PREVIOUSLY_PLACED,
	(CASE WHEN R.APPROVED_REGISTRATION = 'Y' THEN TRUE ELSE FALSE END) AS APPROVED_REGISTRATION, CASE 
        WHEN EXISTS (
            SELECT 1
            FROM {{ source('bounty_jobs', 'party_role') }} PRIN
            WHERE PRIN.PARTY_ID = R.PERSON_ID
            AND PRIN.ROLE_TYPE_CODE = 'BAN'
        ) THEN 1
        ELSE 0
    END AS BANNED_FROM_MARKETPLACE,A.ADDRESS_1,
	A.ADDRESS_2,
	A.POSTAL_CODE,
	A.CITY,
	A.STATE,
	A.COUNTRY,
	COP.EMAIL_ADDRESS AS COMPENSATION_OWNER_EMAIL,
	COP.FIRST_NAME || ' ' || COP.LAST_NAME AS COMPENSATION_OWNER_NAME,AMG.EMAIL_ADDRESS AS ACCOUNT_MANAGER_EMAIL,
	AMG.FIRST_NAME || ' ' || AMG.LAST_NAME AS ACCOUNT_MANAGER_NAME,(CASE WHEN PN.INTERNAL_USER_FLAG = 'Y' THEN TRUE ELSE FALSE END) AS INTERNAL_USER,
	PN.INITIAL_ACTIVATION_DATE,
	R.CANDIDATES_PERM_PERCENT,
	R.CANDIDATES_RETAINED_PERCENT,
	R.CANDIDATES_TEMP_PERCENT,
	R.CANDIDATES_TEMP_TO_PERM_PERCENT,(CASE
		WHEN R.DIVERSITY_SOURCING_PRACTICE = 'UNDERSERVED' THEN 'Underserved'
		WHEN R.DIVERSITY_SOURCING_PRACTICE = 'HIGHLY_DIVERSE' THEN 'Highly Diverse'
		WHEN R.DIVERSITY_SOURCING_PRACTICE = 'NOT_DISADVANTAGED' THEN 'Not Disadvantaged'
		WHEN R.DIVERSITY_SOURCING_PRACTICE = 'NOT_A_FOCUS' THEN 'Not a Focus'
		WHEN R.DIVERSITY_SOURCING_PRACTICE IS NULL THEN 'Not Yet Specified'
	END) AS DIVERSITY_SOURCING_PRACTICE,
	R.DIVERSE_SOURCING_WOMEN,
	R.DIVERSE_SOURCING_VETERAN,
	R.DIVERSE_SOURCING_LGBTQ,
	R.DIVERSE_SOURCING_DISABLED,
	R.DIVERSE_SOURCING_MINORITY,
	R.DIVERSE_CANDIDATES_PERCENT,
	R.DIVERSE_CANDIDATES_CERTIFICATIONS,
	R.DIVERSE_CANDIDATES_NOTES,
	C.DIVERSITY_STATUS_CERTIFIED,
	CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'MBE'
    ) THEN 'Y'
    ELSE 'N'
END AS MINORITY_BUSINESS_ENTERPRISE,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'SDVO'
    ) THEN 'Y'
    ELSE 'N'
END AS SERVICE_DISABLED_VETERAN_OWNED_BUSINESS,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'VO'
    ) THEN 'Y'
    ELSE 'N'
END AS VETERAN_OWNED_BUSINESS,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'WBE'
    ) THEN 'Y'
    ELSE 'N'
END AS WOMEN_BUSINESS_ENTERPRISE,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'DBE'
    ) THEN 'Y'
    ELSE 'N'
END AS DISABLED_OWNED_BUSINESS,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'LBE'
    ) THEN 'Y'
    ELSE 'N'
END AS LGBT_OWNED_BUSINESS,CASE
    WHEN EXISTS (
        SELECT 1
        FROM {{ source('bounty_jobs', 'company_diversity_status') }} CDS
        WHERE CDS.COMPANY_ID = C.COMPANY_ID
        AND CDS.DIVERSITY_STATUS_CODE = 'SBE'
    ) THEN 'Y'
    ELSE 'N'
END AS SMALL_BUSINESS,FS.DESCRIPTION AS FIRM_SIZE,
	(CASE 
		WHEN RS.REFERRAL_CODE_USED IS NOT NULL THEN RS.REFERRAL_CODE_USED
		ELSE REF.RECRUITER_REFERRAL_CODE
	END) AS REFERRAL_CODE,
    rn.name AS COMPANY_REFERRAL,
	(CASE 
		WHEN REL.RELATIONSHIP_ID IS NULL THEN 'Standard' 
		ELSE 'Admin' 
	END) AS USER_TYPE,CASE 
    WHEN R.ATS_FLAG = 1 THEN RAT.DESCRIPTION
    WHEN R.ATS_FLAG = 0 THEN 'No'
    ELSE CAST(R.ATS_FLAG AS VARCHAR) END AS ATS,R.ATS_OTHER AS ATS_FREE_TEXT,
    PN.TERMINATED_FLAG,
    CAST(PN.TERMINATION_DATE AS DATE) AS TERMINATION_DATE,
    I1.NAME AS INDUSTRY1_NAME,
    I2.NAME AS INDUSTRY2_NAME,
    I3.NAME AS INDUSTRY3_NAME,
    J1.NAME AS JOB_CATEGORY1_NAME,
    J2.NAME AS JOB_CATEGORY2_NAME,
    J3.NAME AS JOB_CATEGORY3_NAME
FROM 
	{{ source('bounty_jobs', 'party') }} PT
	JOIN {{ source('bounty_jobs', 'person') }} PN ON PT.PARTY_ID = PN.PERSON_ID 
	JOIN {{ source('bounty_jobs', 'recruiter') }} R ON PN.PERSON_ID = R.PERSON_ID
	JOIN {{ source('bounty_jobs', 'company') }} C ON C.COMPANY_ID = PN.COMPANY_ID
	left join rs_name rn on rn.REFERREE_ID=PN.PERSON_ID 
	LEFT JOIN {{ source('bounty_jobs', 'relationship') }} REL ON REL.SOURCE_PARTY_ID = PN.PERSON_ID AND REL.TARGET_PARTY_ID = PN.COMPANY_ID AND REL.RELATIONSHIP_TYPE_CODE IN ('CA') AND REL.RECORD_STATUS_CODE = 'A' 
	LEFT JOIN {{ source('bounty_jobs', 'firm_size') }} FS ON FS.ID = R.FIRM_SIZE_ID
	LEFT JOIN {{ source('bounty_jobs', 'referrer_status') }} REFS ON REFS.CODE = PN.REFERRER_STATUS_CODE
	LEFT JOIN {{ source('bounty_jobs', 'marketing_question') }} MKTQ on PN.MARKETING_QUESTION_CODE = MKTQ.CODE
	LEFT JOIN {{ source('bounty_jobs', 'name_prefix') }} NP ON PN.NAME_PREFIX_CODE = NP.CODE
	LEFT JOIN {{ source('bounty_jobs', 'person_status') }} PST ON PN.PERSON_STATUS_CODE = PST.CODE
	LEFT JOIN {{ source('bounty_jobs', 'referrer_marketing_status') }} RMKTS on PN.REFERRER_MARKETING_STATUS_CODE = RMKTS.CODE
	LEFT JOIN {{ source('bounty_jobs', 'education_level') }} EL ON EL.CODE = R.EDUCATION_LEVEL_CODE
	LEFT JOIN {{ source('bounty_jobs', 'company_size') }} CS ON CS.ID = R.FIRM_SIZE_ID
	LEFT JOIN {{ source('bounty_jobs', 'recruiter_ats_type') }} RAT ON RAT.CODE = R.ATS
	LEFT JOIN 	(
				SELECT 
					AIN.*
				FROM 
					bounty_jobs.ADDRESS AIN
				JOIN 	(
						SELECT 
							MAX(ADDRESS_ID) ID
						FROM 
							bounty_jobs.ADDRESS
						WHERE 
							ADDRESS_TYPE_CODE = 'PR'
						GROUP BY 
							PARTY_ID
						) MAX_A ON MAX_A.ID = AIN.ADDRESS_ID
				) A ON PT.PARTY_ID = A.PARTY_ID
	LEFT JOIN {{ source('bounty_jobs', 'referral_slot') }} RS on PN.PERSON_ID = RS.REFERREE_ID
	LEFT JOIN {{ source('bounty_jobs', 'person') }} REF ON RS.REFERRER_ID = REF.PERSON_ID
	LEFT JOIN {{ source('bounty_jobs', 'person') }} COP ON C.COMP_OWNER_ID = COP.PERSON_ID
	LEFT JOIN {{ source('bounty_jobs', 'person') }} AMG ON C.ACT_MGR_ID = AMG.PERSON_ID
	LEFT JOIN {{ source('bounty_jobs', 'certification') }} C1 ON C1.CODE = R.CERTIFICATION_CODE_1
	LEFT JOIN {{ source('bounty_jobs', 'certification') }} C2 ON C2.CODE = R.CERTIFICATION_CODE_2
	LEFT JOIN {{ source('bounty_jobs', 'certification') }} C3 ON C3.CODE = R.CERTIFICATION_CODE_3
    LEFT JOIN {{ source('bounty_jobs', 'industry') }} I1 ON R.INDUSTRY_ID_1 = I1.ID
    LEFT JOIN {{ source('bounty_jobs', 'industry') }} I2 ON R.INDUSTRY_ID_2 = I2.ID
    LEFT JOIN {{ source('bounty_jobs', 'industry') }} I3 ON R.INDUSTRY_ID_3 = I3.ID 
    LEFT JOIN {{ source('bounty_jobs', 'job_category') }} J1 ON R.JOB_CATEGORY_ID_1 = J1.ID
    LEFT JOIN {{ source('bounty_jobs', 'job_category') }} J2 ON R.JOB_CATEGORY_ID_2 = J2.ID
    LEFT JOIN {{ source('bounty_jobs', 'job_category') }} J3 ON R.JOB_CATEGORY_ID_3 = J3.ID